function fileName = date2name(experiment,d,well)
% VID483_G2_1_2018y08m17d_01h56m
fileName = strcat(experiment,'_',well,'_1_',string(d.Year),'y',...
    sprintf('%02d', d.Month),'m',sprintf('%02d',d.Day),...
    'd_',sprintf('%02d',d.Hour),'h',sprintf('%02d',d.Minute),'m');
end